### ISSUE TITLE
Recibido

### ISSUE THREAD

**Issue by Nexxtor** [Irivas2009/irmaRivas#1]
Gracias, Irma he recibido la tarea, por favor entrega tambien el link en el moodle, cuando lo hagas cierra este Issues

**Comment by Irivas2009** [comment]
hola, las imagenes del index, schedule y about_us

https://drive.google.com/file/d/1g2GC8CNr81KR8WQy4zSaxWh-TzikHV4z/view?usp=sharing
https://drive.google.com/file/d/1fOzdHFn2tnnOoCG45CfO2Lz0ssxSg-tz/view?usp=sharing
https://drive.google.com/file/d/15MfpGt0O-GGOjB0L07SliDEsypOBmOPb/view?usp=sharing
